accounts/urls.py
from django.urls import include, path
from .views import SignUpView

app_name = "accounts"
urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('signup/', SignUpView.as_view(), name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('habit.urls')),
    path('accounts/', include('accounts.urls')),
    # Django reload
    path("__reload__/", include("django_browser_reload.urls")),
]

habit/urls.py
from django.urls import path
from .views import *


app_name = 'habits'
urlpatterns = [
    # User, all the habits in the current day
    path('', HomeView.as_view(), name="home"),

    # Calendar view
    path('<int:pk>/', CalendarView.as_view(), name="calendar"),

    # Create habit
    path('create/', HabitCreateView.as_view(), name="create"),

    # Update habit
    path('<int:pk>/update/', HabitUpdateView.as_view(), name="update"),

    # Delete habit
    path('<int:pk>/delete/', HabitDeleteView.as_view(), name="delete"),
]

accounts/models.py
from django.db import models

# Create your models here.

habit/models.py
from datetime import datetime
from pytz import timezone

from django.db import models
from django.contrib.auth import get_user_model

from django.conf.global_settings import LANGUAGE_CODE, TIME_ZONE


User = get_user_model()

# Create your models here.
class Habit(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    name = models.CharField(max_length=100)
    description = models.TextField()

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['-created']
    def __str__(self):
        return self.user.username + " - " + self.name


class Daily(models.Model):
    habit = models.ForeignKey(Habit, on_delete=models.CASCADE)
    # Auto now add true makes the field uneditable, 
    # making it impossible to change in Django Admin
    date = models.DateField(blank=True)
    is_active = models.BooleanField(default=True) 

    # Date workaround
    def save(self, *args, **kwargs):
        if not self.date:
            utc = datetime.now()
            tz = timezone(TIME_ZONE)
            today = utc.astimezone(tz)
            self.date = today
        super(Daily, self).save(*args, **kwargs)
    class Meta:
        verbose_name_plural = "Daily habit"

    def __str__(self):
        return str(self.habit) + " - " + str(self.date)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from django import forms

from django.contrib.auth import get_user_model
from django.contrib.auth import views as auth_views




class SignUpForm(UserCreationForm):

    email = forms.EmailField(required=True, widget=forms.EmailInput(
        attrs={'placeholder': 'Email', 'class': 'form-control bg-white border-left-0 border-md'}))
    username = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'placeholder': 'Username', 'class': 'form-control bg-white border-left-0 border-md'}))
    first_name = forms.CharField(max_length=70, widget=forms.TextInput(
        attrs={'placeholder': 'First name', 'class': 'form-control bg-white border-left-0 border-md'}))
    last_name = forms.CharField(max_length=70, widget=forms.TextInput(
        attrs={'placeholder': 'Last name', 'class': 'form-control bg-white border-left-0 border-md'}))

    class Meta:
        model = get_user_model()
        fields = ("first_name", "last_name", 
                  "email", "username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        # self.fields["username"].widget.attrs["class"] = 'form-control bg-white border-left-0 border-md'

        # First password
        self.fields["password1"].widget.attrs["class"] = 'form-control bg-white border-left-0 border-md'
        self.fields["password1"].widget.attrs["placeholder"] = 'Contraseña'

        # Password confirmation
        self.fields["password2"].widget.attrs["class"] = 'form-control bg-white border-left-0 border-md'
        self.fields["password2"].widget.attrs["placeholder"] = 'Confirmar'

accounts/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate
from django.urls import reverse_lazy

from .forms import SignUpForm

class SignUpView(CreateView):
    """
    Allow the User to Create a New Account
    """
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = reverse_lazy('habits:home')
    # If the form is valid it directly login the user and redirect him to the blog.

    def form_valid(self, form):
        to_return = super().form_valid(form)
        user = authenticate(
            username=form.cleaned_data["username"],
            password=form.cleaned_data["password1"],
        )
        login(self.request, user)
        return to_return

habit/views.py
from datetime import datetime
from pytz import timezone

from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import ListView, View, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.shortcuts import get_object_or_404, get_list_or_404

from django.conf.global_settings import LANGUAGE_CODE, TIME_ZONE
from .models import Habit, Daily

utc = datetime.now()
tz = timezone(TIME_ZONE)
today = utc.astimezone(tz)

# Current day
# All the habits of the user in the current day
class HomeView(LoginRequiredMixin, View):
    model = Habit
    template_name = "habits/home.html"


    def get(self, *args, **kwargs):
        context = {}
        queryset = self.model.objects.filter(user=self.request.user)
        context['habits'] = []
        context['today'] = today
        for habit in queryset:
            q = (Daily.objects.filter(habit=habit, date=today, is_active=True))
            context['habits'].append([habit, q])
        return render(self.request, self.template_name, context)

    # Create a daily with the selected habit
    # by checking the box
    def post(self,  *args, **kwargs):
        habit_id = self.request.POST["daily"]
        habit = Habit.objects.get(id=habit_id)
        q = Daily.objects.filter(habit=habit, date=today)
        if not q:
            Daily.objects.create(habit=habit, date=today)
        else:
            q[0].is_active = not (q[0].is_active)
            q[0].save() 

        return redirect('habits:home')

#  Calendar View for specific habit
class CalendarView(LoginRequiredMixin, DetailView):
    model = Habit
    context_object_name = 'habit'
    template_name = 'habits/calendar.html'

    # Get all the days the habit was done
    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['days'] = Daily.objects.filter(habit=self.get_object(), is_active=True)
        return context


class HabitCreateView(LoginRequiredMixin, CreateView):
    template_name = 'habits/create_habit.html'
    model = Habit
    fields = ['name', 'description']

    success_url = reverse_lazy('habits:home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class HabitUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'habits/habit_form.html'
    model = Habit
    fields = ['name', 'description']
    
    success_url = reverse_lazy('habits:home')

class HabitDeleteView(LoginRequiredMixin, DeleteView):
    model = Habit
    template_name = 'confirm_delete.html'
    success_url = reverse_lazy('habits:home')

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />

    {% comment %} Full Calendar {% endcomment %}
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/combine/npm/fullcalendar@5.11.3/main.min.css,npm/fullcalendar@5.11.3/main.min.css"
    />

    <title>{% block title %}{% endblock title %} - Home</title>
  </head>
  <body>
    {% block navbar %}
        {% include 'utils/navbar.html' %}
    {% endblock navbar %}
    <div class="container">
        {% block body %}
        
        
        {% endblock body %}
    </div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"

    >
      </script>
    {% comment %} Full calendar JS {% endcomment %}
    <script src="https://cdn.jsdelivr.net/combine/npm/fullcalendar@5.11.3,npm/fullcalendar@5.11.3/locales-all.min.js,npm/fullcalendar@5.11.3/locales-all.min.js,npm/fullcalendar@5.11.3/main.min.js"></script>
    {% block scripts %}
    {% endblock scripts %}
    <style type="text/css">
      body {
        background: #F1FAEE;
      }
    </style>
  </body>
</html>

templates/confirm_delete.html
{% extends 'base.html' %}

{% block title %}Eliminar {{habit.name}}{% endblock title %}

{% block body %}
<div  
style="border: solid; border-radius: 10px; width: 100%; height: unset; margin-top: 10px; background-color: #f3f3f3;">
    <h1 style="text-align: center;margin-left: 10px;">Eliminar {{habit.name}}</h1>
    <br>
    <p style="text-align: start; width: 70%; margin-left: 25%;">¿Estas seguro de eliminar tu hábito <b>{{habit.name}}</b>? Esta acción no se puede reversar.</p>
    <br>
    <form action="" method="post" style="text-align: center; width: 100%; ">
        {% csrf_token %}
        <a class="btn" href="{% url 'habits:home' %}" 
        style=" border-radius: 5px; color: aliceblue; background-color: #1D3557;" > Cancelar </a>
        <button type="submit" class="btn" style="background-color: #E63946; color: white;">Eliminar</button>
    </form>
    <br>
    <br>

</div>
{% endblock body %}

templates/habits/calendar.html
{% extends 'base.html' %}
{% block title %}{{habit.name | capfirst}} Calendar {% endblock title %}

{% block body %}
<div class="text-center center" style="background-color: white;">
    <h1>{{habit.name}}</h1>
    <p class="my-2">{{habit.description}}</p>
    <div class="my-4 ">
        <div id="calendar" class="text-capitalize" style="margin-left: 10px; margin-right: 10px; margin-bottom: 10px;"></div>
    </div>
</div>

{% endblock body %}

{% block scripts %}
<script>
    document.addEventListener('DOMContentLoaded', function(){
        var calendarUI = document.getElementById('calendar');
        var calendar = new FullCalendar.Calendar(calendarUI,{
            events: [
                {% for day in days %}
                {
                    title: 'Hecho este dia',
                    start: '{{ day.date | date:"Y-m-d"}}',
                    end: '{{ day.date | date:"Y-m-d" }}',
                },
                {% endfor %} 
            ],
            locale: 'es',
        });
        calendar.render();
    });
</script>
{% endblock scripts %}

templates/habits/create_habit.html
{% extends 'base.html' %}

{% block title %}Crear Habito{% endblock title %}

{% block body %}
<div  
style="border: solid; border-radius: 10px; width: 100%; height: unset; margin-top: 10px; background-color: #f3f3f3;">
        <h1 style="text-align: center;margin-left: 10px;"> Crea tu hábito!!! </h1>
        <form action="#" method="post" style="text-align: start; width: 70%;margin-left: 25%;">
            {% csrf_token %}
            
            <label>Nombre del Hábito:</label><br>
            <input 
            placeholder="Ingrese el nombre del habito, minimo de 3 caracteres" 
            minlength="3" 
            type="text" 
            id="fname" 
            name="name" 
            style="min-width: 100; width: inherit; background-color: #eef9fa;">
            <br>
            <br>
            
            <label>En que consiste el hábito:</label><br>
            <textarea 
            id="Descripcion" 
            name="description"
            placeholder="Ingrese la descripción del habito, minimo de 3 caracteres" 
            minlength="3" 
            type="text" 
            id="Descripcion" 
            style="  width: inherit; height: 100px;display: inline; vertical-align:  top; background-color: #eef9fa;" 
            ></textarea>
            
            <br>
            <br>
            
            <button class="btn" 
            type="submit" 
            style=" color: white; background-color: #457B9D;">Crear</button>
            <a class="btn" href="{% url 'habits:home' %}" 
        style=" border-radius: 5px; color: aliceblue; background-color: #1D3557;" > Cancelar </a>
            <br>
            <br>
        </form>
    </div>
{% endblock body %}

templates/habits/habit_form.html
{% extends 'base.html' %}

{% block title %}Edit Habit {{habit.name}} {% endblock title %}

{% block body %}
<div  
style="border: solid; border-radius: 10px; width: 100%; height: unset; margin-top: 10px; background-color: #f3f3f3;">
        <h1 style="text-align: center;margin-left: 10px;">Edición del habito {{habit.name}} </h1>
        <form action="#" method="post" style="text-align: start; width: 70%;margin-left: 25%;">
            {% csrf_token %}
            
            <label>Nombre del Hábito:</label><br>
            <input 
            placeholder="Ingrese el nombre del habito, minimo de 3 caracteres" 
            minlength="3" 
            type="text" 
            id="fname" 
            name="name" 
            style="min-width: 100; width: inherit; background-color: #eef9fa;">
            <br>
            <br>
            
            <label>En que consiste el hábito:</label><br>
            <textarea 
            id="Descripcion" 
            name="description"
            placeholder="Ingrese la descripción del habito, minimo de 3 caracteres" 
            minlength="3" 
            type="text" 
            id="Descripcion" 
            style="  width: inherit; height: 100px;display: inline; vertical-align:  top; background-color: #eef9fa;" 
            ></textarea>
            
            <br>
            <br>
            
            <button class="btn" 
            type="submit" 
            style=" color: white; background-color: #457B9D;">Editar</button>
            <a class="btn" href="{% url 'habits:home' %}" 
        style=" border-radius: 5px; color: aliceblue; background-color: #1D3557;" > Cancelar </a>
            <br>
            <br>
        </form>
    </div>


{% endblock body %}

templates/habits/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}


{% block body %}
{% comment %} Definitions {% endcomment %}
{% now "d" as day %}
{% now "l" as day_name %}
{% now "F" as month %}
<div class="my-3 center text-center">
    <h1 class="">Hoy es {{day_name | capfirst}} {{day}} de {{month | capfirst}}</h1>
</div>
<div class="">
    <h4>
        Hola {{user.username}}, estos son tus habitos {{daily}}
    </h4>
</div>
<div class="center">
    <ul class="list-group">
        {% for habit, daily in habits %}
            <li class="list-group-item">
                <h4>
                <a href="{% url 'habits:calendar' habit.pk %}">{{habit.name}}</a>
                </h4>
                <p>
                <button type="button" class="btn btn-primary" style="background-color: #457B9D;"><a href="{% url 'habits:update' habit.pk %}" class="link-success">Editar</a></button>
                <button type="button" class="btn" style=" border-radius: 5px; color: aliceblue; background-color: #E63946;"><a href="{% url 'habits:delete' habit.pk %}" class="link-danger" >Eliminar</a></button>
                </p>
                <form name="formCheckbox" action="" method="POST" id="formCheckbox{{forloop.counter}}">
                    {% csrf_token %}
                    <input type="hidden" name="daily" value="{{habit.pk}}"/>
                    <input type="checkbox" class="form-check"  id="checkBox" {% if daily%}checked{% endif %} onchange="document.getElementById('formCheckbox{{forloop.counter}}').submit()">
                </form>
            </li>
        {% empty %}
            <li class="list-group-item">
                <p>Lo sentimos, no tienes habitos. <a href="{% url 'habits:create' %}" class="link" style="color: Blue;">Crea uno!</a></p>
            </li>   
        {% endfor %}
        
    </ul>
</div>
<style type="text/css">
    .list-group-item{
        padding: 1rem 3rem;
        border: solid 2px #1d3557;
        margin: 0.1rem 0rem;
    }
    h4 a {
        color: #1d3557;
    }
    h4 a:hover {
        color: #457b9d;
    }
    a {
        color: white;
    }
    a:hover {
        color: #c7cee7
    }
    .list-group-item form {
        float: right;
        margin-right: 5%;
        margin-top: -5%;
    }
    
</style>

{% endblock body %}

templates/utils/navbar.html
<nav class=" mb-4 navbar navbar-dark navbar-expand-lg bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'habits:home' %}">Home</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
          <a
            aria-current="page"
            href="{% url 'habits:create' %}"
            >Crear Habito</a
          >

    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'habits:create' %}"
            >Crear Habito</a
          >
        </li>
      </ul>
    </div>

    {% comment %} Sign in {% endcomment %}
    
    {% if user.is_authenticated %}
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle" 
        type="button" id="dropdownMenuButton" 
        data-toggle="dropdown" 
        aria-haspopup="true" 
        aria-expanded="false">

          Hola {{user.username}}
        </button>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton" style="width: 4px">
          <a class="dropdown-item" href="{%url 'accounts:logout' %}" >Salir</a>
        </div>
      </div>

    {% else %}
    <a class="btn btn-danger" href="{% url 'accounts:login' %}">Entra</a>
    {% endif %}
  </div>
  <style type="text/css">
    .navbar {
      background: rgb(80,111,120);
      background: linear-gradient(180deg, rgba(80,111,120,1) 85%, rgba(159,219,236,1) 100%);
    }
    body > nav > div > p {
      padding: 0rem 1rem;
    }
    body > nav > div > a:nth-child(5){
      padding: 0rem 1rem;
      margin-top: -1.3%;
    }
  </style>
</nav>